import { afterEach, expect, it } from 'vitest';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { createStoryServer } from '../apps/api/server.ts';
import { fixture, testConfig } from './helpers.ts';

const cleanups: Array<() => Promise<void>> = [];
afterEach(async () => { while (cleanups.length) await cleanups.pop()!(); });

it('runs choice, narration retry and deadline handling through MCP and the v2 API', async () => {
  const value = await fixture(); cleanups.push(value.close);
  const service = await createStoryServer({ database: value.database, startWorker: false, logger: false }); cleanups.push(() => service.app.close());
  const address = await service.app.listen({ host: '127.0.0.1', port: 0 });
  const client = new Client({ name: 'v2-test', version: '2.0.0' }, { capabilities: {} });
  const transport = new StdioClientTransport({ command: process.execPath, args: ['--import', 'tsx', 'apps/mcp/main.ts'], cwd: process.cwd(), env: { ...process.env, STORY_API_URL: `${address}/api/v2` } as Record<string, string>, stderr: 'pipe' });
  cleanups.push(() => client.close()); await client.connect(transport);
  const call = async (name: string, args: Record<string, unknown>) => {
    const response: any = await client.callTool({ name, arguments: args });
    if (response.isError) throw new Error(response.content[0].text);
    return response.structuredContent.result;
  };
  const story = await service.store.create('local-player', testConfig(), 20260906); const storyId = story.storyId;
  const outline = await service.runtime.generateOutline(storyId); outline.stages[0].entryCriteria = ['玩家选择调查路线'];
  await service.store.confirmOutline(storyId, undefined, outline);
  const start = await call('story_send', { storyId, input: '讨论路线', idempotencyKey: 'mcp-opening-001' }); await service.runtime.runTurn(start.id);
  let state = await call('story_get_state', { storyId }); expect(state.pendingDecision).not.toBeNull();
  const request = { storyId, decisionId: state.pendingDecision.id, optionId: state.pendingDecision.options[0].id, idempotencyKey: 'mcp-decision-001' };
  const resolved = await call('story_resolve_choice', request); expect((await call('story_resolve_choice', request)).continuationTurnId).toBe(resolved.continuationTurnId);
  await service.runtime.runTurn(resolved.continuationTurnId);
  const finished = await call('story_wait', { storyId, turnId: resolved.continuationTurnId, timeoutSeconds: 1 }); expect(finished.status).toBe('completed');
  expect((await service.store.turn(start.id)).continuationTurnId).toBe(finished.id);
  const hashes = await service.store.stateHashes(storyId);
  const retry = await call('story_retry_narration', { storyId, sceneId: finished.scene.id, idempotencyKey: 'mcp-narration-001' }); await service.runtime.runTurn(retry.turnId);
  expect((await service.store.stateHashes(storyId)).stateHash).toBe(hashes.stateHash);
  state = await call('story_get_state', { storyId });
  await service.store.editStage(storyId, { ...state.activeStage, deadlineMinutes: state.clock });
  state = await call('story_get_state', { storyId });
  const blocked = await service.app.inject({ method: 'POST', url: `/api/v2/stories/${storyId}/turns`, payload: { input: '被阻止', source: 'web', idempotencyKey: 'deadline-blocked' } });
  expect(blocked.statusCode).toBe(409); expect(blocked.json().code).toBe('STAGE_DEADLINE_REQUIRES_REVIEW');
  await call('story_resolve_deadline', { storyId, stageId: state.activeStage.id, revision: state.activeStage.revision, action: 'extend', deadlineMinutes: state.clock + 360, idempotencyKey: 'mcp-deadline-001' });
  const ordinary = state.scenes.at(-1).options[0];
  const next = await call('story_send', { storyId, input: ordinary.text, sceneId: finished.scene.id, optionId: ordinary.id, idempotencyKey: 'mcp-ordinary-001' });
  expect(next.source).toBe('codex'); await service.runtime.runTurn(next.id);
  const tools = (await client.listTools()).tools.map(tool => tool.name); expect(tools).toContain('story_resume_autoplay');
  const wrongStory = await service.store.create('local-player', testConfig(), 1);
  const scoped = await service.app.inject({ method: 'GET', url: `/api/v2/stories/${wrongStory.storyId}/turns/${next.id}` }); expect(scoped.statusCode).toBe(404);
  expect((await service.store.stateHashes(storyId)).matches).toBe(true);
  const newer=await call('story_create',{title:'扩展接口验收',genre:'science_fiction',premise:'核对记录',provider:'deterministic',romanceMode:'off',rulesAtStart:false,seed:15});const nextId=newer.storyId;
  await call('story_generate_outline',{storyId:nextId});await call('story_confirm_outline',{storyId:nextId});
  const panel=await call('story_resource_panel',{storyId:nextId});expect(panel.enabled).toBe(false);
  await call('story_enable_resources',{storyId:nextId,setup:{panels:panel.resources.panels,items:panel.resources.items,challenges:panel.resources.challenges,idempotencyKey:'mcp-enable-resources'}});
  const intent={actorId:'protagonist',targetId:'local_obstacle',method:'investigate',itemId:null,evidenceFactIds:[]};const quote=await call('story_action_quote',{storyId:nextId,intent});expect(quote.cost).toBe(5);
  const action=await call('story_send',{storyId:nextId,input:'调查登记障碍',resourceIntent:intent,idempotencyKey:'mcp-resource-action'});await service.runtime.runTurn(action.id);
  const history=await call('story_history',{storyId:nextId});expect(history.items).toHaveLength(1);expect(history.items[0].claims.length).toBeGreaterThan(0);
  expect((await call('story_actions',{storyId:nextId})).items).toHaveLength(1);expect((await call('story_chapters',{storyId:nextId})).chapters).toHaveLength(1);
  await call('story_memory_index',{storyId:nextId,action:'pause'});expect((await call('story_memory_search',{storyId:nextId,query:'调查'})).job.status).toBe('paused');
  const saved=await call('story_export_save',{storyId:nextId});const restored=await call('story_import_save',{archive:saved,idempotencyKey:'mcp-extended-import'});expect(restored.paused).toBe(true);
  const checkpoint=(await call('story_checkpoints',{storyId:nextId})).checkpoints[0];expect((await call('story_fork',{storyId:nextId,checkpointId:checkpoint.id,idempotencyKey:'mcp-extended-fork'})).storyId).not.toBe(nextId);
  expect((await call('story_npc_activity',{storyId:nextId})).goals).toEqual([]);expect((await call('story_metrics',{storyId:nextId})).scenes).toBe(1);
}, 60000);
