import React, { useEffect, useState } from 'react';
import type { Scene, StoryStateView, StoryThread } from '../../../packages/contracts/index.ts';

export async function experienceApi(path: string, body?: unknown, method = body === undefined ? 'GET' : 'POST') {
  const response = await fetch(`/api/v2${path}`, { method, headers: body === undefined ? {} : { 'content-type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) });
  const data = await response.json(); if (!response.ok) throw new Error(typeof data.error==='string'?data.error:data.code??'请求失败'); return data;
}
export function Evidence({ scene,storyId }: { scene: Pick<Scene, 'claims' | 'segments'>;storyId?:string }) {
  const [facts,setFacts]=useState<any[]>([]),[error,setError]=useState('');
  return <details className="event-evidence" onToggle={e=>{if(e.currentTarget.open&&storyId&&!facts.length)void experienceApi(`/stories/${storyId}/facts/read`,{ids:[...new Set(scene.claims.flatMap(c=>c.factIds))].slice(0,50)}).then(v=>setFacts(v.facts)).catch(e=>setError(e.message));}}><summary>事件依据{scene.claims.length ? ` · ${scene.claims.length} 项` : ' · 尚未建立逐项引用'}</summary>{scene.claims.map(claim => <p key={claim.id}><b>{({ event: '已发生', reported: '人物说法', uncertain: '未确认' })[claim.mode]}</b> {claim.text}<small>{claim.factIds.map(id=>facts.find(f=>f.id===id)?.text??id).join('；')}</small></p>)}{error&&<p role="alert">{error}</p>}</details>;
}
export function Experience({ state, refresh }: { state: StoryStateView; refresh(): void }) {
  const [view, setView] = useState('history');
  return <section className="page experience-page"><nav className="experience-tabs" aria-label="历史与记忆">{[['history','历史阅读'],['actions','行动记录'],['chapters','章节回顾'],['memory','相关记忆'],['saves','存档与分叉']].map(([id,name]) => <button key={id} className={view === id ? 'primary' : 'secondary'} onClick={() => setView(id)}>{name}</button>)}</nav>{view === 'history' ? <History key={state.id} storyId={state.id}/> : view === 'memory' ? <Memory key={state.id} storyId={state.id}/> : view === 'saves' ? <Saves storyId={state.id}/> : <Records key={`${state.id}-${view}`} storyId={state.id} chapters={view === 'chapters'}/>}</section>;
}
export function Saves({ storyId }: { storyId?: string }) {
  const [recoveries,setRecoveries]=useState<any[]>([]);
  const [checkpoints,setCheckpoints] = useState<any[]>([]), [error,setError] = useState(''), [notice,setNotice] = useState(''), [busy,setBusy] = useState(false);
  useEffect(() => { if (storyId) void experienceApi(`/stories/${storyId}/checkpoints`).then(v => setCheckpoints(v.checkpoints)).catch(e => setError(e.message)); },[storyId]);
  useEffect(()=>{if(storyId)void experienceApi(`/stories/${storyId}/recovery`).then(v=>setRecoveries(v.turns)).catch(e=>setError(e.message));},[storyId]);
  const perform = async (operation: () => Promise<void>) => { if(busy)return; setBusy(true);setError('');try{await operation();}catch(e){setError((e as Error).message);}finally{setBusy(false);} };
  const download = (checkpointId?:string) => perform(async () => { const save = await experienceApi(`/stories/${storyId}/save${checkpointId ? `?checkpointId=${checkpointId}` : ''}`); const url=URL.createObjectURL(new Blob([JSON.stringify(save)],{type:'application/json'})); const link=document.createElement('a');link.href=url;link.download=`story-${storyId}-scene-${save.sceneSeq}.srpg.json`;link.click();URL.revokeObjectURL(url);setNotice(`已导出至第 ${save.sceneSeq} 场、事件 ${save.factSeq} 的检查点。`); });
  const importFile = (file:File) => perform(async () => { const archive=JSON.parse(await file.text());const result=await experienceApi('/saves/import',{archive,idempotencyKey:`import-${crypto.randomUUID()}`});window.dispatchEvent(new CustomEvent('srpg:open-save',{detail:result.storyId}));setNotice(`已恢复为独立存档 ${result.storyId}，自动推进保持暂停。可从故事列表打开。`); });
  return <section className="panel history-scene"><h1>存档与分叉</h1><p>导出使用明确的可恢复节点；正在处理但尚未进入该节点的行动不会包含在文件中。</p>{storyId && <button className="primary" disabled={busy} onClick={() => void download()}>导出最新检查点</button>}<label>恢复存档<input type="file" accept=".json,.srpg.json" disabled={busy} onChange={e => {const file=e.target.files?.[0];if(file)void importFile(file);e.target.value='';}}/></label>{error && <p role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}{recoveries.map(turn=><article key={turn.id}><p>{turn.input}</p><button className="secondary" disabled={busy} onClick={()=>void perform(async()=>{await experienceApi(`/stories/${storyId}/turns/${turn.id}/retry`,{idempotencyKey:`resume-${turn.id}`});setRecoveries(old=>old.filter(t=>t.id!==turn.id));setNotice('已恢复该节点的处理。');})}>{turn.scene_id?'恢复缺失正文':'恢复尚未执行的行动'}</button></article>)}{checkpoints.map(cp => <article className="history-scene" key={cp.id}><b>第 {cp.scene_seq} 场 · {cp.label}</b><div className="action-row"><button className="secondary" disabled={busy} onClick={() => void download(cp.id)}>导出此节点</button><button className="secondary" disabled={busy} onClick={() => void perform(async () => { const result=await experienceApi(`/stories/${storyId}/forks`,{checkpointId:cp.id,idempotencyKey:`fork-${crypto.randomUUID()}`});window.dispatchEvent(new CustomEvent('srpg:open-save',{detail:result.storyId}));setNotice(`已创建分支 ${result.storyId}，父存档保持原状。`); })}>从此处分叉</button></div></article>)}</section>;
}
function History({ storyId }: { storyId: string }) {
  const readKey = `srpg:reader:v1:${storyId}`;
  const [cursor, setCursor] = useState<string | undefined>(() => { try { return JSON.parse(localStorage.getItem(readKey) ?? '{}').cursor; } catch { return undefined; } });
  const [page, setPage] = useState<{ items: Scene[]; nextCursor: string | null } | null>(null);
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  useEffect(() => { let cancelled = false; setLoading(true); setError(''); experienceApi(`/stories/${storyId}/history${cursor ? `?cursor=${encodeURIComponent(cursor)}` : ''}`).then(value => { if (!cancelled) { setPage(value); localStorage.setItem(readKey, JSON.stringify({ cursor })); } }).catch(e => { if (!cancelled) setError(e.message); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [storyId, cursor]);
  return <div className="reader"><header><h1>历史阅读</h1><button className="secondary" onClick={() => { setCursor(undefined); if (!cursor) void experienceApi(`/stories/${storyId}/history`).then(setPage).catch(e => setError(e.message)); }}>回到最新</button></header>{error && <p role="alert">{error}</p>}{loading && <p role="status">正在读取历史…</p>}{page?.items.slice().reverse().map(scene => <article className="panel history-scene" key={scene.id} id={`scene-${scene.id}`}><small>第 {scene.seq} 场 · 故事分钟 {scene.startTime}–{scene.endTime} · {scene.location}</small><h2>{scene.title}</h2><div className="history-prose">{scene.prose}</div><Evidence scene={scene} storyId={storyId}/><button className="secondary" disabled={loading} onClick={async()=>{setLoading(true);try{const checkpoint=await experienceApi(`/stories/${storyId}/checkpoints/rebuild`,{sceneId:scene.id});const fork=await experienceApi(`/stories/${storyId}/forks`,{checkpointId:checkpoint.checkpointId,idempotencyKey:`fork-history-${crypto.randomUUID()}`});window.dispatchEvent(new CustomEvent('srpg:open-save',{detail:fork.storyId}));}catch(e){setError((e as Error).message);}finally{setLoading(false);}}}>从这一场分叉</button>{scene.options.length > 0 && <details><summary>当时的建议行动（历史记录）</summary><ul>{scene.options.map(option => <li key={option.id}>{option.text}</li>)}</ul></details>}</article>)}{!page?.items.length && !loading && <p>尚无历史场景。</p>}{page?.nextCursor && <button className="secondary" disabled={loading} onClick={() => { setCursor(page.nextCursor!); window.scrollTo({ top: 0 }); }}>阅读更早的 20 场</button>}</div>;
}
function Records({ storyId, chapters }: { storyId: string; chapters: boolean }) {
  const [cursor,setCursor]=useState<string|null>(null);
  const [data, setData] = useState<any[]>([]), [error, setError] = useState(''), [recaps, setRecaps] = useState<Record<string, any>>({}), [busy, setBusy] = useState('');
  useEffect(() => { let active = true; experienceApi(`/stories/${storyId}/${chapters ? 'chapters' : 'actions'}`).then(result => { if (active){setData(result.chapters ?? result.items);setCursor(result.nextCursor??null);} }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [storyId, chapters]);
  const recap = async (stageId: string) => { setBusy(stageId); try { const value = await experienceApi(`/stories/${storyId}/chapters/${stageId}/recap`, {}); setRecaps(old => ({ ...old, [stageId]: value })); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } };
  return <div><h1>{chapters ? '章节回顾' : '行动记录'}</h1>{error && <p role="alert">{error}</p>}{data.map(item => <article className="panel history-scene" key={item.stageId ?? item.id}>{chapters ? <><h2>{item.title}</h2><p>{item.outcome ?? '进行中'}</p>{item.scenes.map((s: any) => <p key={s.id}>第 {s.seq} 场 · {s.summary}</p>)}<button className="secondary" disabled={!!busy || !item.scenes.length} onClick={() => void recap(item.stageId)}>{busy === item.stageId ? '正在生成回顾…' : '生成叙事回顾'}</button>{recaps[item.stageId] && <div className="history-prose">{recaps[item.stageId].prose}<small>来源 {recaps[item.stageId].sourceFactIds.length} 条事件 · {recaps[item.stageId].mode === 'fallback' ? '事件简述' : '语义检查通过'}</small></div>}</> : <><h2>{item.input}</h2><p>{item.status} · {item.scene_seq ? `后果：第 ${item.scene_seq} 场` : '尚无提交后果'}</p>{item.decision && <p>已确认：{item.decision.choice}</p>}{item.error && <p>{item.error}</p>}</>}</article>)}{cursor&&!chapters&&<button className="secondary" disabled={!!busy} onClick={async()=>{setBusy('actions');try{const result=await experienceApi(`/stories/${storyId}/actions?cursor=${encodeURIComponent(cursor)}`);setData(old=>[...old,...result.items]);setCursor(result.nextCursor);}catch(e){setError((e as Error).message);}finally{setBusy('');}}}>读取更早的行动</button>}</div>;
}
function Memory({ storyId }: { storyId: string }) {
  const [q, setQ] = useState(''), [data, setData] = useState<any>(null), [error, setError] = useState('');
  const load = async () => { try { setData(await experienceApi(`/stories/${storyId}/memory?q=${encodeURIComponent(q)}`)); setError(''); } catch (e) { setError((e as Error).message); } };
  useEffect(() => { void load(); }, [storyId]);
  return <div><h1>相关记忆</h1><form className="action-row" onSubmit={e => { e.preventDefault(); void load(); }}><input aria-label="记忆查询" value={q} onChange={e => setQ(e.target.value)} placeholder="人物、地点、旧承诺…"/><button className="primary">检索</button></form>{error && <p role="alert">{error}</p>}{data?.job && <section className="panel history-scene"><p>历史整理：{data.job.status} · {data.job.cursor}/{data.job.target_seq}</p>{data.job.error && <p>{data.job.error}</p>}<button className="secondary" onClick={() => void experienceApi(`/stories/${storyId}/memory/index`, { action: data.job.status === 'running' ? 'pause' : 'resume' }).then(load).catch(e => setError(e.message))}>{data.job.status === 'running' ? '暂停整理' : '继续整理'}</button></section>}{data?.threads.map((thread: StoryThread) => <article className="panel history-scene" key={thread.id}><h2>{thread.title}</h2><p>{({ open: '未解决', resolved: '已解决', cancelled: '已取消' })[thread.status]} · {thread.verified ? '有审查证据' : '历史索引候选'}</p>{thread.sourceQuotes.map((quote, i) => <blockquote key={i}>{quote}</blockquote>)}</article>)}{data?.facts.map((fact: any) => <article className="panel history-scene" key={fact.id}><small>事实 #{fact.seq}</small><p>{fact.text}</p></article>)}</div>;
}
