import React,{useEffect,useState} from 'react';
import type {StoryStateView,ResourceState,ResourceIntent} from '../../../packages/contracts/index.ts';
import {experienceApi} from './experience.tsx';

const labels:Record<string,string>={sneak:'潜入',negotiate:'交涉',force:'强攻',investigate:'调查',rest:'休息',long_rest:'长休',meditate:'调息',technique:'施展术式',illuminate:'照明',shield:'护盾',unlock:'开锁法术',hack:'设备入侵',recharge:'充能',treat:'治疗',trade:'交易',reward:'领取奖励'};
export function Mechanics({state,refresh}:{state:StoryStateView;refresh():void}){
  const [data,setData]=useState<{enabled:boolean;resources:ResourceState}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[target,setTarget]=useState('local_obstacle'),[method,setMethod]=useState('investigate'),[quote,setQuote]=useState<any>(null),[notice,setNotice]=useState(''),[selectedItem,setSelectedItem]=useState('');
  const hero=state.characters.find(c=>c.importance==='protagonist')!;
  useEffect(()=>{let active=true;experienceApi(`/stories/${state.id}/resources`).then(v=>{if(active){setData(v);setQuote(null);}}).catch(e=>setError(e.message));return()=>{active=false;};},[state.id,state.revision]);
  const run=async(task:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');try{await task();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  if(!data)return <p>{error||'正在读取角色面板…'}</p>;
  const panel=data.resources.panels[hero.id],challenge=data.resources.challenges.find(c=>c.id===target);
  const ownedItems=data.resources.items.filter(i=>i.ownerId===hero.id&&!i.consumed);
  const restores=['rest','long_rest',...(ownedItems.some(i=>i.id.startsWith('medical_'))?['treat']:[]),...(data.resources.ruleset==='cultivation'?['meditate']:[]),...(data.resources.ruleset==='western_fantasy'?['illuminate','shield']:[])];
  const methods=[...new Set([...(challenge?.methods??[]),...restores])];
  const usableItems=ownedItems.filter(i=>method==='treat'?i.id.startsWith('medical_'):true);
  const itemId=['hack','treat'].includes(method)?(usableItems.some(i=>i.id===selectedItem)?selectedItem:usableItems[0]?.id??null):null;
  const intent:ResourceIntent={actorId:hero.id,targetId:target,method:method as ResourceIntent['method'],itemId,evidenceFactIds:[]};
  const unavailable=busy||state.status==='finished'||!!state.pendingDecision||!!state.activeStage?.awaitingDeadline||state.activeStage?.status!=='active'||!!state.latestTurn&&['queued','assembling','directing','reviewing','repairing','committing','narrating','summarizing'].includes(state.latestTurn.status);
  return <section className="page panel mechanics"><h1>角色面板与行动</h1><p>{hero.name} · 规则版本 {data.resources.version} · {data.enabled?'已启用':'尚未启用，可调整初始面板'}</p>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}<div className="resource-grid">{(['stamina','injury','money','energy','spellSlots'] as const).map(key=><label key={key}>{({stamina:'体力',injury:'伤势（0 无伤，3 失能）',money:'金钱',energy:data.resources.ruleset==='science_fiction'?'电量':'灵力',spellSlots:'法术槽'})[key]}<input type="number" min="0" max={key==='stamina'?100:key==='injury'||key==='spellSlots'?3:key==='energy'?30:100000000} value={panel[key]} readOnly={data.enabled} onChange={e=>setData({...data,resources:{...data.resources,panels:{...data.resources.panels,[hero.id]:{...panel,[key]:Number(e.target.value)}}}})}/></label>)}</div><p>体能 {panel.attributes.physical} · 洞察 {panel.attributes.insight} · 社交 {panel.attributes.social}；潜入 {panel.skills.sneak} · 交涉 {panel.skills.negotiate} · 强攻 {panel.skills.force} · 调查 {panel.skills.investigate}</p><p>物品：{data.resources.items.filter(i=>i.ownerId===hero.id&&!i.consumed).map(i=>i.name).join('、')||'无'}；追踪程度 {panel.trace}</p>
    {!data.enabled?<><p>确认后从当前节点开始计算资源，不倒算过去的消耗。</p><button className="primary" disabled={busy} onClick={()=>void run(async()=>{await experienceApi(`/stories/${state.id}/resources/enable`,{panels:data.resources.panels,items:data.resources.items,challenges:data.resources.challenges,idempotencyKey:`enable-${crypto.randomUUID()}`});refresh();})}>确认面板并启用规则</button></>:<><label>行动目标<select value={target} onChange={e=>{setTarget(e.target.value);setMethod(data.resources.challenges.find(c=>c.id===e.target.value)?.methods[0]??'rest');setQuote(null);}}>{data.resources.challenges.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>行动方式<select value={method} onChange={e=>{setMethod(e.target.value);setQuote(null);}}>{methods.map(m=><option key={m} value={m}>{labels[m]}</option>)}</select></label>{["hack","treat"].includes(method)&&<label>使用物品<select value={itemId??""} onChange={e=>{setSelectedItem(e.target.value);setQuote(null);}}>{!usableItems.length&&<option value="">没有可用物品</option>}{usableItems.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<button className="secondary" disabled={unavailable} onClick={()=>void run(async()=>setQuote(await experienceApi(`/stories/${state.id}/resources/quote`,intent)))}>查看代价</button>{quote&&<div className="notice"><p>{quote.label}：体力 {quote.cost}，金钱 {quote.money}，{quote.minutes} 故事分钟。{quote.costNotes?.length>0&&`${quote.costNotes.join('；')}。`}{quote.dc!==null&&`难度 ${quote.dc}，修正 ${quote.modifier}，成功机会 ${Math.round(quote.probability*100)}%。失败仍扣尝试成本。`}</p><button className="primary" disabled={unavailable} onClick={()=>void run(async()=>{const turn=await experienceApi(`/stories/${state.id}/turns`,{input:`${labels[method]}：${challenge?.title??'当前地点'}`,resourceIntent:intent,source:'web',idempotencyKey:`resource-${crypto.randomUUID()}`});setNotice(`行动已进入处理队列，请在故事页查看这一场后果。`);setQuote(null);refresh();})}>执行这一行动</button></div>}</>}
    <details><summary>已结算的判定</summary>{data.resources.attempts.slice(-20).reverse().map(a=><p key={a.key}>{a.result} {a.roll!==null&&`骰点 ${a.roll}`} · 体力 −{a.cost} · {a.minutes} 分钟</p>)}</details>
  </section>;
}
export function NpcActivity({state}:{state:StoryStateView}){const [data,setData]=useState<any>(null),[error,setError]=useState('');useEffect(()=>{let active=true;experienceApi(`/stories/${state.id}/npcs`).then(v=>{if(active)setData(v);}).catch(e=>setError(e.message));return()=>{active=false;};},[state.id,state.revision]);return <section className="page panel"><h1>人物动态与预警</h1>{error&&<p role="alert">{error}</p>}{!data?.goals.length&&<p>目前没有可知的待处理动态。</p>}{data?.goals.map((g:any)=><article className="history-scene" key={g.id}><h2>{g.title}</h2><p>{state.characters.find(c=>c.id===g.actorId)?.name} · {({pending:'进行中',warned:'已收到预警',completed:'已执行',cancelled:'已取消'} as Record<string,string>)[g.status]}</p>{g.status==='warned'&&<p>最早在故事分钟 {g.warningClock+60}、且你至少行动一次后产生后果。可以在故事页输入干预行动。</p>}</article>)}</section>;}
export function GraphEditor({state,refresh}:{state:StoryStateView;refresh():void}){const [raw,setRaw]=useState(()=>JSON.stringify(state.outline,null,2)),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <details className="json-editor"><summary>完整路线大纲（含未开放路线，剧透）</summary><p>只允许修改尚未执行的节点与连接，保存后将重新计算当前可选路线。</p><textarea aria-label="完整路线大纲" value={raw} onChange={e=>setRaw(e.target.value)}/>{error&&<p role="alert">{error}</p>}<button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await experienceApi(`/stories/${state.id}/graph`,{revision:state.outline?.graph?.revision??1,outline:JSON.parse(raw)},'PUT');refresh();setError('已保存。');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>保存未来路线</button></details>;}
